# Generated by Django 4.2.13 on 2024-05-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portbuilder', '0005_alter_contactinfo_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='github',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='twitter',
        ),
    ]
