# Generated by Django 4.2.13 on 2024-05-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portbuilder', '0006_rename_github_sociallink_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='url',
            new_name='github',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
