# Generated by Django 4.2.13 on 2024-05-20 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portbuilder', '0008_rename_github_sociallink_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='url',
            new_name='github',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='platform',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
