# Generated by Django 4.2.13 on 2024-05-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portbuilder', '0009_rename_url_sociallink_github_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='github',
            new_name='url1',
        ),
        migrations.RenameField(
            model_name='sociallink',
            old_name='linkedin',
            new_name='url2',
        ),
        migrations.RenameField(
            model_name='sociallink',
            old_name='twitter',
            new_name='url3',
        ),
    ]
