# Generated by Django 4.2.13 on 2024-05-21 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portbuilder', '0010_rename_github_sociallink_url1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='url1',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='url2',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='url3',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], default='boys', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
