# Generated by Django 4.2.13 on 2024-06-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portbuilder', '0014_work_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_exp',
            name='end_date',
            field=models.DateField(blank=True, default='Today', null=True),
        ),
    ]
