# Generated by Django 4.2.13 on 2024-06-03 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portbuilder', '0015_alter_work_exp_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_exp',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
