# Generated by Django 4.2.13 on 2024-06-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portbuilder', '0016_alter_work_exp_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_picture',
            field=models.ImageField(blank=True, null=True, upload_to='project_pictures/'),
        ),
    ]
