# Generated by Django 4.2.13 on 2024-06-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portbuilder', '0017_project_project_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, help_text='Link to the project', max_length=400),
        ),
    ]
