# Generated by Django 4.2.13 on 2024-06-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portbuilder', '0018_alter_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(blank=True, help_text='Socials', max_length=400, null=True),
        ),
    ]
